import { NextResponse } from "next/server"
import { auth } from "@/lib/auth"
import { prisma } from "@/lib/prisma"
import { jsPDF } from "jspdf"

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ sheetId: string }> }
) {
  const session = await auth()
  if (!session?.user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  const { sheetId } = await params

  const sheet = await prisma.practiceSheet.findUnique({
    where: { id: sheetId },
    include: {
      student: { select: { name: true, studentNumber: true } },
      items: {
        orderBy: { sortOrder: "asc" },
        include: {
          question: {
            include: {
              knowledgePoints: {
                include: {
                  knowledgePoint: { select: { name: true } },
                },
              },
            },
          },
        },
      },
    },
  })

  if (!sheet) {
    return NextResponse.json({ error: "练习单不存在" }, { status: 404 })
  }

  const doc = new jsPDF({ unit: "mm", format: "a4" })
  doc.setFont("helvetica", "normal")

  // Header
  doc.setFontSize(16)
  doc.text("Biology Practice Sheet", 20, 20)
  doc.setFontSize(10)
  doc.text(`Student: ${sheet.student.name}`, 20, 30)
  doc.text(`Student ID: ${sheet.student.studentNumber || "N/A"}`, 20, 36)
  doc.text(`Week: ${sheet.weekLabel}`, 20, 42)
  doc.text(`Date: ${new Date().toLocaleDateString("en-US")}`, 20, 48)

  doc.setDrawColor(200, 200, 200)
  doc.line(20, 52, 190, 52)

  let y = 62
  const pageHeight = 277
  const margin = 20

  for (const item of sheet.items) {
    const q = item.question
    const qLabel = item.isReview ? "[Review]" : "[New]"
    const kpNames = q.knowledgePoints
      .map((k: any) => k.knowledgePoint.name)
      .join(", ")

    if (y > pageHeight - 40) {
      doc.addPage()
      y = margin
    }

    doc.setFontSize(9)
    doc.setTextColor(100, 100, 100)
    doc.text(
      `${item.sortOrder}. ${qLabel} | Type: ${q.questionType} | Difficulty: ${q.difficulty} | KPs: ${kpNames}`,
      margin,
      y
    )
    y += 6

    doc.setFontSize(11)
    doc.setTextColor(0, 0, 0)
    const contentLines = doc.splitTextToSize(
      q.content,
      170
    ) as string[]
    doc.text(contentLines, margin, y)
    y += contentLines.length * 5.5 + 4

    if (q.questionType === "CHOICE" && q.options && Array.isArray(q.options)) {
      for (const opt of q.options as { label: string; text: string }[]) {
        if (y > pageHeight - 20) {
          doc.addPage()
          y = margin
        }
        doc.setFontSize(10)
        doc.text(`${opt.label}. ${opt.text}`, margin + 5, y)
        y += 5
      }
      y += 2
    }

    y += 12
    doc.setDrawColor(230, 230, 230)
    doc.line(margin, y, 190, y)
    y += 6
  }

  if (y > pageHeight - 15) {
    doc.addPage()
    y = margin
  }
  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text(
    "Generated by ZhiJiao Helper - Biology Practice Platform",
    20,
    y + 8
  )

  const pdfBuffer = Buffer.from(doc.output("arraybuffer"))

  return new NextResponse(pdfBuffer, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="sheet-${sheet.weekLabel}-${sheet.student.name}.pdf"`,
    },
  })
}
